-- AlterTable
ALTER TABLE "FeePolicy" ALTER COLUMN "fixed_amount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "percentage" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "percent_base_field" SET DATA TYPE TEXT,
ALTER COLUMN "min_amount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "max_amount" SET DATA TYPE DECIMAL(65,30);
